version: "2.3"
   
services:
  sket_cpu:

    build: 
      context: .
      dockerfile: ./docker-sket_server-config/docker_sket_cpu/Dockerfile

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: bash -c 'python manage.py runserver 0.0.0.0:8000'
    
    
  sket_gpu:
    runtime: nvidia
    environment:
        - NVIDIA_VISIBLE_DEVICES=all

    build: 
      context: .
      dockerfile: ./docker-sket_server-config/docker_sket_gpu/Dockerfile

    volumes:
      - .:/code
    ports:
      - "8001:8001"
    command: bash -c 'python3 manage.py runserver 0.0.0.0:8001'